export interface Destination {
  slug: string;
  city: string;
  country: string;
  countryCode: string;
  lat: number;
  lon: number;
  description: string;
  funPlaces: string[];
  similarDestinations: string[];
  moods: string[];
  region: string;
}

export const MOODS = [
  { id: "adventurous", label: "Adventurous", emoji: "sword" },
  { id: "relaxed", label: "Relaxed", emoji: "palm" },
  { id: "cultural", label: "Cultural", emoji: "temple" },
  { id: "romantic", label: "Romantic", emoji: "heart" },
  { id: "foodie", label: "Foodie", emoji: "ramen" },
  { id: "nature", label: "Nature", emoji: "mountain" },
  { id: "party", label: "Party", emoji: "disco" },
  { id: "spiritual", label: "Spiritual", emoji: "lotus" },
  { id: "happy", label: "Happy", emoji: "smile" },
  { id: "sad", label: "Sad", emoji: "rain" },
  { id: "excited", label: "Excited", emoji: "star" },
  { id: "curious", label: "Curious", emoji: "magnify" },
] as const;

export type MoodId = (typeof MOODS)[number]["id"];

export const destinations: Destination[] = [
  {
    slug: "tokyo-japan",
    city: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    lat: 35.6762,
    lon: 139.6503,
    description: "A dazzling fusion of ultra-modern technology and ancient tradition.",
    funPlaces: ["Shibuya Crossing", "Senso-ji Temple", "Akihabara Electric Town", "Tsukiji Outer Market", "Meiji Shrine"],
    similarDestinations: ["seoul-south-korea", "osaka-japan", "taipei-taiwan"],
    moods: ["excited", "cultural", "foodie", "curious"],
    region: "Asia",
  },
  {
    slug: "paris-france",
    city: "Paris",
    country: "France",
    countryCode: "FR",
    lat: 48.8566,
    lon: 2.3522,
    description: "The City of Light, where every street corner tells a story of art and romance.",
    funPlaces: ["Eiffel Tower", "Louvre Museum", "Montmartre", "Seine River Cruise", "Le Marais"],
    similarDestinations: ["rome-italy", "barcelona-spain", "vienna-austria"],
    moods: ["romantic", "cultural", "foodie", "happy"],
    region: "Europe",
  },
  {
    slug: "rome-italy",
    city: "Rome",
    country: "Italy",
    countryCode: "IT",
    lat: 41.9028,
    lon: 12.4964,
    description: "The Eternal City where ancient ruins meet vibrant modern life.",
    funPlaces: ["Colosseum", "Vatican Museums", "Trevi Fountain", "Trastevere", "Pantheon"],
    similarDestinations: ["paris-france", "athens-greece", "florence-italy"],
    moods: ["cultural", "romantic", "foodie", "happy"],
    region: "Europe",
  },
  {
    slug: "bali-indonesia",
    city: "Bali",
    country: "Indonesia",
    countryCode: "ID",
    lat: -8.3405,
    lon: 115.092,
    description: "A tropical paradise of terraced rice paddies, temples, and surf breaks.",
    funPlaces: ["Ubud Rice Terraces", "Tanah Lot Temple", "Seminyak Beach", "Mount Batur Sunrise Trek", "Sacred Monkey Forest"],
    similarDestinations: ["phuket-thailand", "colombo-sri-lanka", "hanoi-vietnam"],
    moods: ["relaxed", "spiritual", "nature", "romantic"],
    region: "Asia",
  },
  {
    slug: "new-york-usa",
    city: "New York",
    country: "United States",
    countryCode: "US",
    lat: 40.7128,
    lon: -74.006,
    description: "The city that never sleeps — iconic skyline, world-class culture, and endless energy.",
    funPlaces: ["Central Park", "Times Square", "Brooklyn Bridge", "Metropolitan Museum", "Broadway Shows"],
    similarDestinations: ["london-uk", "chicago-usa", "toronto-canada"],
    moods: ["excited", "party", "cultural", "adventurous"],
    region: "North America",
  },
  {
    slug: "london-uk",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    lat: 51.5074,
    lon: -0.1278,
    description: "A royal city of history, theater, and afternoon tea.",
    funPlaces: ["Tower of London", "British Museum", "Camden Market", "West End Theatre", "Hyde Park"],
    similarDestinations: ["new-york-usa", "paris-france", "edinburgh-uk"],
    moods: ["cultural", "curious", "happy", "party"],
    region: "Europe",
  },
  {
    slug: "marrakech-morocco",
    city: "Marrakech",
    country: "Morocco",
    countryCode: "MA",
    lat: 31.6295,
    lon: -7.9811,
    description: "A sensory explosion of spice markets, mosaics, and desert mystique.",
    funPlaces: ["Jemaa el-Fnaa Square", "Majorelle Garden", "Bahia Palace", "Medina Souks", "Atlas Mountain Day Trip"],
    similarDestinations: ["istanbul-turkey", "cairo-egypt", "fez-morocco"],
    moods: ["adventurous", "cultural", "curious", "foodie"],
    region: "Africa",
  },
  {
    slug: "kyoto-japan",
    city: "Kyoto",
    country: "Japan",
    countryCode: "JP",
    lat: 35.0116,
    lon: 135.7681,
    description: "A serene city of bamboo groves, tea ceremonies, and ancient temples.",
    funPlaces: ["Fushimi Inari Shrine", "Arashiyama Bamboo Grove", "Kinkaku-ji", "Gion District", "Nishiki Market"],
    similarDestinations: ["tokyo-japan", "nara-japan", "taipei-taiwan"],
    moods: ["spiritual", "relaxed", "cultural", "sad"],
    region: "Asia",
  },
  {
    slug: "rio-de-janeiro-brazil",
    city: "Rio de Janeiro",
    country: "Brazil",
    countryCode: "BR",
    lat: -22.9068,
    lon: -43.1729,
    description: "Samba, sun, and spectacular vistas from Sugarloaf to Copacabana.",
    funPlaces: ["Christ the Redeemer", "Copacabana Beach", "Sugarloaf Mountain", "Lapa Arches", "Tijuca Forest"],
    similarDestinations: ["buenos-aires-argentina", "cartagena-colombia", "havana-cuba"],
    moods: ["party", "happy", "adventurous", "excited"],
    region: "South America",
  },
  {
    slug: "reykjavik-iceland",
    city: "Reykjavik",
    country: "Iceland",
    countryCode: "IS",
    lat: 64.1466,
    lon: -21.9426,
    description: "A gateway to glaciers, geysers, and the Northern Lights.",
    funPlaces: ["Blue Lagoon", "Golden Circle", "Northern Lights Tour", "Hallgrimskirkja", "Whale Watching"],
    similarDestinations: ["tromso-norway", "helsinki-finland", "edinburgh-uk"],
    moods: ["nature", "adventurous", "sad", "spiritual"],
    region: "Europe",
  },
  {
    slug: "istanbul-turkey",
    city: "Istanbul",
    country: "Turkey",
    countryCode: "TR",
    lat: 41.0082,
    lon: 28.9784,
    description: "Where East meets West — a city straddling two continents.",
    funPlaces: ["Hagia Sophia", "Grand Bazaar", "Blue Mosque", "Bosphorus Cruise", "Topkapi Palace"],
    similarDestinations: ["marrakech-morocco", "athens-greece", "cairo-egypt"],
    moods: ["cultural", "curious", "foodie", "adventurous"],
    region: "Europe",
  },
  {
    slug: "cape-town-south-africa",
    city: "Cape Town",
    country: "South Africa",
    countryCode: "ZA",
    lat: -33.9249,
    lon: 18.4241,
    description: "Where mountains meet the ocean — vineyards, penguins, and Table Mountain.",
    funPlaces: ["Table Mountain", "Cape of Good Hope", "Boulders Beach Penguins", "V&A Waterfront", "Stellenbosch Wine Route"],
    similarDestinations: ["nairobi-kenya", "rio-de-janeiro-brazil", "sydney-australia"],
    moods: ["nature", "adventurous", "happy", "relaxed"],
    region: "Africa",
  },
  {
    slug: "bangkok-thailand",
    city: "Bangkok",
    country: "Thailand",
    countryCode: "TH",
    lat: 13.7563,
    lon: 100.5018,
    description: "A city of golden temples, floating markets, and legendary street food.",
    funPlaces: ["Grand Palace", "Wat Pho", "Chatuchak Weekend Market", "Khao San Road", "Chao Phraya River"],
    similarDestinations: ["hanoi-vietnam", "phuket-thailand", "bali-indonesia"],
    moods: ["foodie", "party", "adventurous", "excited"],
    region: "Asia",
  },
  {
    slug: "sydney-australia",
    city: "Sydney",
    country: "Australia",
    countryCode: "AU",
    lat: -33.8688,
    lon: 151.2093,
    description: "Harbor views, golden beaches, and a laid-back coastal lifestyle.",
    funPlaces: ["Sydney Opera House", "Bondi Beach", "Harbour Bridge Climb", "Royal Botanic Garden", "The Rocks"],
    similarDestinations: ["melbourne-australia", "auckland-new-zealand", "cape-town-south-africa"],
    moods: ["happy", "relaxed", "nature", "adventurous"],
    region: "Oceania",
  },
  {
    slug: "buenos-aires-argentina",
    city: "Buenos Aires",
    country: "Argentina",
    countryCode: "AR",
    lat: -34.6037,
    lon: -58.3816,
    description: "The Paris of South America — tango, steak, and colorful neighborhoods.",
    funPlaces: ["La Boca", "Recoleta Cemetery", "San Telmo Market", "Teatro Colón", "Puerto Madero"],
    similarDestinations: ["rio-de-janeiro-brazil", "santiago-chile", "montevideo-uruguay"],
    moods: ["romantic", "foodie", "cultural", "party"],
    region: "South America",
  },
  {
    slug: "amsterdam-netherlands",
    city: "Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    lat: 52.3676,
    lon: 4.9041,
    description: "Canals, bicycles, world-class museums, and a free-spirited atmosphere.",
    funPlaces: ["Anne Frank House", "Van Gogh Museum", "Vondelpark", "Jordaan District", "Canal Cruise"],
    similarDestinations: ["copenhagen-denmark", "brussels-belgium", "berlin-germany"],
    moods: ["relaxed", "curious", "cultural", "happy"],
    region: "Europe",
  },
  {
    slug: "cairo-egypt",
    city: "Cairo",
    country: "Egypt",
    countryCode: "EG",
    lat: 30.0444,
    lon: 31.2357,
    description: "Home of the Pyramids — where millennia of civilization still breathe.",
    funPlaces: ["Great Pyramids of Giza", "Egyptian Museum", "Khan el-Khalili Bazaar", "Nile Felucca Ride", "Citadel of Saladin"],
    similarDestinations: ["istanbul-turkey", "marrakech-morocco", "petra-jordan"],
    moods: ["curious", "cultural", "adventurous", "spiritual"],
    region: "Africa",
  },
  {
    slug: "cusco-peru",
    city: "Cusco",
    country: "Peru",
    countryCode: "PE",
    lat: -13.532,
    lon: -71.9675,
    description: "Gateway to Machu Picchu and the heart of the Inca Empire.",
    funPlaces: ["Machu Picchu", "Sacred Valley", "Plaza de Armas", "Rainbow Mountain", "San Pedro Market"],
    similarDestinations: ["la-paz-bolivia", "quito-ecuador", "bogota-colombia"],
    moods: ["adventurous", "spiritual", "nature", "curious"],
    region: "South America",
  },
  {
    slug: "barcelona-spain",
    city: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    lat: 41.3874,
    lon: 2.1686,
    description: "Gaudí's dreamscape meets Mediterranean beaches and tapas bars.",
    funPlaces: ["Sagrada Familia", "Park Güell", "La Rambla", "Gothic Quarter", "Barceloneta Beach"],
    similarDestinations: ["paris-france", "rome-italy", "lisbon-portugal"],
    moods: ["happy", "foodie", "romantic", "party"],
    region: "Europe",
  },
  {
    slug: "prague-czech-republic",
    city: "Prague",
    country: "Czech Republic",
    countryCode: "CZ",
    lat: 50.0755,
    lon: 14.4378,
    description: "A fairy-tale city of cobblestones, Gothic spires, and world-famous beer.",
    funPlaces: ["Charles Bridge", "Prague Castle", "Old Town Square", "Astronomical Clock", "Petřín Hill"],
    similarDestinations: ["vienna-austria", "budapest-hungary", "krakow-poland"],
    moods: ["romantic", "cultural", "sad", "curious"],
    region: "Europe",
  },
  {
    slug: "dubai-uae",
    city: "Dubai",
    country: "UAE",
    countryCode: "AE",
    lat: 25.2048,
    lon: 55.2708,
    description: "A futuristic oasis of skyscrapers, luxury malls, and desert adventures.",
    funPlaces: ["Burj Khalifa", "Dubai Mall", "Desert Safari", "Palm Jumeirah", "Dubai Marina"],
    similarDestinations: ["abu-dhabi-uae", "doha-qatar", "singapore-singapore"],
    moods: ["excited", "party", "adventurous", "happy"],
    region: "Asia",
  },
  {
    slug: "hanoi-vietnam",
    city: "Hanoi",
    country: "Vietnam",
    countryCode: "VN",
    lat: 21.0285,
    lon: 105.8542,
    description: "Ancient pagodas, bustling streets, and the world's best pho.",
    funPlaces: ["Hoan Kiem Lake", "Old Quarter", "Ho Chi Minh Mausoleum", "Temple of Literature", "Ha Long Bay Day Trip"],
    similarDestinations: ["bangkok-thailand", "bali-indonesia", "tokyo-japan"],
    moods: ["foodie", "curious", "adventurous", "cultural"],
    region: "Asia",
  },
  {
    slug: "lisbon-portugal",
    city: "Lisbon",
    country: "Portugal",
    countryCode: "PT",
    lat: 38.7223,
    lon: -9.1393,
    description: "Pastel-colored hills, melancholic fado music, and custard tarts.",
    funPlaces: ["Belém Tower", "Tram 28", "Time Out Market", "Alfama District", "Jerónimos Monastery"],
    similarDestinations: ["barcelona-spain", "porto-portugal", "seville-spain"],
    moods: ["sad", "romantic", "relaxed", "foodie"],
    region: "Europe",
  },
  {
    slug: "nairobi-kenya",
    city: "Nairobi",
    country: "Kenya",
    countryCode: "KE",
    lat: -1.2921,
    lon: 36.8219,
    description: "Gateway to African safaris — where wildlife roams free.",
    funPlaces: ["Nairobi National Park", "Giraffe Centre", "Karen Blixen Museum", "Maasai Mara Day Trip", "David Sheldrick Elephant Orphanage"],
    similarDestinations: ["cape-town-south-africa", "dar-es-salaam-tanzania", "kampala-uganda"],
    moods: ["nature", "adventurous", "excited", "curious"],
    region: "Africa",
  },
  {
    slug: "santorini-greece",
    city: "Santorini",
    country: "Greece",
    countryCode: "GR",
    lat: 36.3932,
    lon: 25.4615,
    description: "White-washed cliffs over impossibly blue seas — a sunset lover's dream.",
    funPlaces: ["Oia Sunset", "Red Beach", "Akrotiri Ruins", "Wine Tasting", "Fira to Oia Hike"],
    similarDestinations: ["mykonos-greece", "amalfi-italy", "dubrovnik-croatia"],
    moods: ["romantic", "relaxed", "happy", "spiritual"],
    region: "Europe",
  },
  {
    slug: "seoul-south-korea",
    city: "Seoul",
    country: "South Korea",
    countryCode: "KR",
    lat: 37.5665,
    lon: 126.978,
    description: "K-pop capital meets centuries-old palaces — tradition and trend collide.",
    funPlaces: ["Gyeongbokgung Palace", "Myeongdong Shopping", "N Seoul Tower", "Bukchon Hanok Village", "Hongdae Nightlife"],
    similarDestinations: ["tokyo-japan", "taipei-taiwan", "osaka-japan"],
    moods: ["excited", "foodie", "party", "curious"],
    region: "Asia",
  },
  {
    slug: "havana-cuba",
    city: "Havana",
    country: "Cuba",
    countryCode: "CU",
    lat: 23.1136,
    lon: -82.3666,
    description: "Vintage cars, salsa rhythms, and colonial architecture frozen in time.",
    funPlaces: ["Malecón Seawall", "Old Havana", "Plaza de la Catedral", "Tropicana Show", "El Floridita Bar"],
    similarDestinations: ["rio-de-janeiro-brazil", "cartagena-colombia", "san-juan-puerto-rico"],
    moods: ["party", "cultural", "romantic", "happy"],
    region: "North America",
  },
  {
    slug: "singapore-singapore",
    city: "Singapore",
    country: "Singapore",
    countryCode: "SG",
    lat: 1.3521,
    lon: 103.8198,
    description: "A garden city of futuristic architecture and legendary hawker food.",
    funPlaces: ["Gardens by the Bay", "Marina Bay Sands", "Hawker Centres", "Sentosa Island", "Little India"],
    similarDestinations: ["tokyo-japan", "dubai-uae", "hong-kong-china"],
    moods: ["foodie", "excited", "curious", "happy"],
    region: "Asia",
  },
  {
    slug: "petra-jordan",
    city: "Petra",
    country: "Jordan",
    countryCode: "JO",
    lat: 30.3285,
    lon: 35.4444,
    description: "The Rose City — an ancient wonder carved into sandstone cliffs.",
    funPlaces: ["The Treasury", "The Monastery", "Siq Canyon", "Petra by Night", "Royal Tombs"],
    similarDestinations: ["cairo-egypt", "marrakech-morocco", "istanbul-turkey"],
    moods: ["adventurous", "spiritual", "curious", "nature"],
    region: "Asia",
  },
  {
    slug: "vancouver-canada",
    city: "Vancouver",
    country: "Canada",
    countryCode: "CA",
    lat: 49.2827,
    lon: -123.1207,
    description: "Mountains meet ocean — a nature lover's urban paradise.",
    funPlaces: ["Stanley Park", "Granville Island", "Grouse Mountain", "Gastown", "Capilano Suspension Bridge"],
    similarDestinations: ["seattle-usa", "portland-usa", "toronto-canada"],
    moods: ["nature", "relaxed", "happy", "adventurous"],
    region: "North America",
  },
];

// Mood to destination matching algorithm
export function getDestinationsByMood(moodId: string): Destination[] {
  // Primary matches: destinations that have this mood
  const primary = destinations.filter((d) => d.moods.includes(moodId));

  // Sort by how prominently the mood features (earlier in moods array = more relevant)
  primary.sort((a, b) => {
    const aIndex = a.moods.indexOf(moodId);
    const bIndex = b.moods.indexOf(moodId);
    return aIndex - bIndex;
  });

  return primary;
}

export function getRandomDestination(): Destination {
  return destinations[Math.floor(Math.random() * destinations.length)];
}

export function getDestinationBySlug(slug: string): Destination | undefined {
  return destinations.find((d) => d.slug === slug);
}

// Top destinations for the "popular" section
export const popularDestinations = [
  "paris-france",
  "tokyo-japan",
  "rome-italy",
  "new-york-usa",
  "london-uk",
  "barcelona-spain",
  "bali-indonesia",
  "istanbul-turkey",
  "dubai-uae",
  "bangkok-thailand",
  "santorini-greece",
  "sydney-australia",
  "rio-de-janeiro-brazil",
  "singapore-singapore",
  "cape-town-south-africa",
  "prague-czech-republic",
  "marrakech-morocco",
  "kyoto-japan",
  "amsterdam-netherlands",
  "cusco-peru",
];
