export interface Destination {
  slug: string;
  city: string;
  country: string;
  countryCode: string;
  lat: number;
  lon: number;
  description: string;
  funPlaces: string[];
  similarDestinations: string[];
  moods: string[];
  region: string;
}

export const MOODS = [
  { id: "adventurous", label: "Adventurous", emoji: "sword" },
  { id: "relaxed", label: "Relaxed", emoji: "palm" },
  { id: "cultural", label: "Cultural", emoji: "temple" },
  { id: "romantic", label: "Romantic", emoji: "heart" },
  { id: "foodie", label: "Foodie", emoji: "ramen" },
  { id: "nature", label: "Nature", emoji: "mountain" },
  { id: "party", label: "Party", emoji: "disco" },
  { id: "spiritual", label: "Spiritual", emoji: "lotus" },
  { id: "happy", label: "Happy", emoji: "smile" },
  { id: "sad", label: "Sad", emoji: "rain" },
  { id: "excited", label: "Excited", emoji: "star" },
  { id: "curious", label: "Curious", emoji: "magnify" },
] as const;

export type MoodId = (typeof MOODS)[number]["id"];

export const destinations: Destination[] = [
  {
    slug: "tokyo-japan",
    city: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    lat: 35.6762,
    lon: 139.6503,
    description: "A dazzling fusion of ultra-modern technology and ancient tradition.",
    funPlaces: ["Shibuya Crossing", "Senso-ji Temple", "Akihabara Electric Town", "Tsukiji Outer Market", "Meiji Shrine"],
    similarDestinations: ["seoul-south-korea", "osaka-japan", "taipei-taiwan"],
    moods: ["excited", "cultural", "foodie", "curious"],
    region: "Asia",
  },
  {
    slug: "paris-france",
    city: "Paris",
    country: "France",
    countryCode: "FR",
    lat: 48.8566,
    lon: 2.3522,
    description: "The City of Light, where every street corner tells a story of art and romance.",
    funPlaces: ["Eiffel Tower", "Louvre", "Montmartre", "Seine", "Le Marais"],
    similarDestinations: ["rome-italy", "barcelona-spain", "vienna-austria"],
    moods: ["romantic", "cultural", "foodie", "happy"],
    region: "Europe",
  },
  {
    slug: "rome-italy",
    city: "Rome",
    country: "Italy",
    countryCode: "IT",
    lat: 41.9028,
    lon: 12.4964,
    description: "The Eternal City where ancient ruins meet vibrant modern life.",
    funPlaces: ["Colosseum", "Vatican Museums", "Trevi Fountain", "Trastevere", "Pantheon"],
    similarDestinations: ["paris-france", "athens-greece", "florence-italy"],
    moods: ["cultural", "romantic", "foodie", "happy"],
    region: "Europe",
  },
  {
    slug: "bali-indonesia",
    city: "Bali",
    country: "Indonesia",
    countryCode: "ID",
    lat: -8.3405,
    lon: 115.092,
    description: "A tropical paradise of terraced rice paddies, temples, and surf breaks.",
    funPlaces: ["Tegallalang Rice Terraces", "Tanah Lot", "Seminyak", "Mount Batur", "Ubud Monkey Forest"],
    similarDestinations: ["phuket-thailand", "colombo-sri-lanka", "hanoi-vietnam"],
    moods: ["relaxed", "spiritual", "nature", "romantic"],
    region: "Asia",
  },
  {
    slug: "new-york-usa",
    city: "New York",
    country: "United States",
    countryCode: "US",
    lat: 40.7128,
    lon: -74.006,
    description: "The city that never sleeps — iconic skyline, world-class culture, and endless energy.",
    funPlaces: ["Central Park", "Times Square", "Brooklyn Bridge", "Metropolitan Museum of Art", "Broadway Theatre"],
    similarDestinations: ["london-uk", "chicago-usa", "toronto-canada"],
    moods: ["excited", "party", "cultural", "adventurous"],
    region: "North America",
  },
  {
    slug: "london-uk",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    lat: 51.5074,
    lon: -0.1278,
    description: "A royal city of history, theater, and afternoon tea.",
    funPlaces: ["Tower of London", "British Museum", "Camden Market", "West End Theatre", "Hyde Park"],
    similarDestinations: ["new-york-usa", "paris-france", "edinburgh-uk"],
    moods: ["cultural", "curious", "happy", "party"],
    region: "Europe",
  },
  {
    slug: "marrakech-morocco",
    city: "Marrakech",
    country: "Morocco",
    countryCode: "MA",
    lat: 31.6295,
    lon: -7.9811,
    description: "A sensory explosion of spice markets, mosaics, and desert mystique.",
    funPlaces: ["Jemaa el-Fnaa", "Majorelle Garden", "Bahia Palace", "Souk of Marrakech", "Atlas Mountains"],
    similarDestinations: ["istanbul-turkey", "cairo-egypt", "fez-morocco"],
    moods: ["adventurous", "cultural", "curious", "foodie"],
    region: "Africa",
  },
  {
    slug: "kyoto-japan",
    city: "Kyoto",
    country: "Japan",
    countryCode: "JP",
    lat: 35.0116,
    lon: 135.7681,
    description: "A serene city of bamboo groves, tea ceremonies, and ancient temples.",
    funPlaces: ["Fushimi Inari-taisha", "Arashiyama", "Kinkaku-ji", "Gion", "Nishiki Market"],
    similarDestinations: ["tokyo-japan", "nara-japan", "taipei-taiwan"],
    moods: ["spiritual", "relaxed", "cultural", "sad"],
    region: "Asia",
  },
  {
    slug: "rio-de-janeiro-brazil",
    city: "Rio de Janeiro",
    country: "Brazil",
    countryCode: "BR",
    lat: -22.9068,
    lon: -43.1729,
    description: "Samba, sun, and spectacular vistas from Sugarloaf to Copacabana.",
    funPlaces: ["Christ the Redeemer (statue)", "Copacabana, Rio de Janeiro", "Sugarloaf Mountain", "Carioca Aqueduct", "Tijuca Forest"],
    similarDestinations: ["buenos-aires-argentina", "cartagena-colombia", "havana-cuba"],
    moods: ["party", "happy", "adventurous", "excited"],
    region: "South America",
  },
  {
    slug: "reykjavik-iceland",
    city: "Reykjavik",
    country: "Iceland",
    countryCode: "IS",
    lat: 64.1466,
    lon: -21.9426,
    description: "A gateway to glaciers, geysers, and the Northern Lights.",
    funPlaces: ["Blue Lagoon (geothermal spa)", "Golden Circle (Iceland)", "Aurora Borealis", "Hallgrímskirkja", "Whale watching"],
    similarDestinations: ["tromso-norway", "helsinki-finland", "edinburgh-uk"],
    moods: ["nature", "adventurous", "sad", "spiritual"],
    region: "Europe",
  },
  {
    slug: "istanbul-turkey",
    city: "Istanbul",
    country: "Turkey",
    countryCode: "TR",
    lat: 41.0082,
    lon: 28.9784,
    description: "Where East meets West — a city straddling two continents.",
    funPlaces: ["Hagia Sophia", "Grand Bazaar", "Blue Mosque", "Bosphorus Cruise", "Topkapi Palace"],
    similarDestinations: ["marrakech-morocco", "athens-greece", "cairo-egypt"],
    moods: ["cultural", "curious", "foodie", "adventurous"],
    region: "Europe",
  },
  {
    slug: "cape-town-south-africa",
    city: "Cape Town",
    country: "South Africa",
    countryCode: "ZA",
    lat: -33.9249,
    lon: 18.4241,
    description: "Where mountains meet the ocean — vineyards, penguins, and Table Mountain.",
    funPlaces: ["Table Mountain", "Cape of Good Hope", "Boulders Beach", "V&A Waterfront", "Stellenbosch"],
    similarDestinations: ["nairobi-kenya", "rio-de-janeiro-brazil", "sydney-australia"],
    moods: ["nature", "adventurous", "happy", "relaxed"],
    region: "Africa",
  },
  {
    slug: "bangkok-thailand",
    city: "Bangkok",
    country: "Thailand",
    countryCode: "TH",
    lat: 13.7563,
    lon: 100.5018,
    description: "A city of golden temples, floating markets, and legendary street food.",
    funPlaces: ["Grand Palace", "Wat Pho", "Chatuchak Weekend Market", "Khao San Road", "Chao Phraya River"],
    similarDestinations: ["hanoi-vietnam", "phuket-thailand", "bali-indonesia"],
    moods: ["foodie", "party", "adventurous", "excited"],
    region: "Asia",
  },
  {
    slug: "sydney-australia",
    city: "Sydney",
    country: "Australia",
    countryCode: "AU",
    lat: -33.8688,
    lon: 151.2093,
    description: "Harbor views, golden beaches, and a laid-back coastal lifestyle.",
    funPlaces: ["Sydney Opera House", "Bondi Beach", "Sydney Harbour Bridge", "Royal Botanic Garden, Sydney", "The Rocks, Sydney"],
    similarDestinations: ["melbourne-australia", "auckland-new-zealand", "cape-town-south-africa"],
    moods: ["happy", "relaxed", "nature", "adventurous"],
    region: "Oceania",
  },
  {
    slug: "buenos-aires-argentina",
    city: "Buenos Aires",
    country: "Argentina",
    countryCode: "AR",
    lat: -34.6037,
    lon: -58.3816,
    description: "The Paris of South America — tango, steak, and colorful neighborhoods.",
    funPlaces: ["La Boca", "Recoleta Cemetery", "San Telmo Market", "Teatro Colón", "Puerto Madero"],
    similarDestinations: ["rio-de-janeiro-brazil", "santiago-chile", "montevideo-uruguay"],
    moods: ["romantic", "foodie", "cultural", "party"],
    region: "South America",
  },
  {
    slug: "amsterdam-netherlands",
    city: "Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    lat: 52.3676,
    lon: 4.9041,
    description: "Canals, bicycles, world-class museums, and a free-spirited atmosphere.",
    funPlaces: ["Anne Frank House", "Van Gogh Museum", "Vondelpark", "Jordaan", "Canals of Amsterdam"],
    similarDestinations: ["copenhagen-denmark", "brussels-belgium", "berlin-germany"],
    moods: ["relaxed", "curious", "cultural", "happy"],
    region: "Europe",
  },
  {
    slug: "cairo-egypt",
    city: "Cairo",
    country: "Egypt",
    countryCode: "EG",
    lat: 30.0444,
    lon: 31.2357,
    description: "Home of the Pyramids — where millennia of civilization still breathe.",
    funPlaces: ["Great Pyramid of Giza", "Egyptian Museum", "Khan el-Khalili", "Nile River", "Cairo Citadel"],
    similarDestinations: ["istanbul-turkey", "marrakech-morocco", "petra-jordan"],
    moods: ["curious", "cultural", "adventurous", "spiritual"],
    region: "Africa",
  },
  {
    slug: "cusco-peru",
    city: "Cusco",
    country: "Peru",
    countryCode: "PE",
    lat: -13.532,
    lon: -71.9675,
    description: "Gateway to Machu Picchu and the heart of the Inca Empire.",
    funPlaces: ["Machu Picchu", "Sacred Valley", "Plaza de Armas", "Rainbow Mountain", "San Pedro Market"],
    similarDestinations: ["la-paz-bolivia", "quito-ecuador", "bogota-colombia"],
    moods: ["adventurous", "spiritual", "nature", "curious"],
    region: "South America",
  },
  {
    slug: "barcelona-spain",
    city: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    lat: 41.3874,
    lon: 2.1686,
    description: "Gaudí's dreamscape meets Mediterranean beaches and tapas bars.",
    funPlaces: ["Sagrada Família", "Park Güell", "La Rambla", "Gothic Quarter, Barcelona", "Barceloneta"],
    similarDestinations: ["paris-france", "rome-italy", "lisbon-portugal"],
    moods: ["happy", "foodie", "romantic", "party"],
    region: "Europe",
  },
  {
    slug: "prague-czech-republic",
    city: "Prague",
    country: "Czech Republic",
    countryCode: "CZ",
    lat: 50.0755,
    lon: 14.4378,
    description: "A fairy-tale city of cobblestones, Gothic spires, and world-famous beer.",
    funPlaces: ["Charles Bridge", "Prague Castle", "Old Town Square", "Astronomical Clock", "Petřín Hill"],
    similarDestinations: ["vienna-austria", "budapest-hungary", "krakow-poland"],
    moods: ["romantic", "cultural", "sad", "curious"],
    region: "Europe",
  },
  {
    slug: "dubai-uae",
    city: "Dubai",
    country: "UAE",
    countryCode: "AE",
    lat: 25.2048,
    lon: 55.2708,
    description: "A futuristic oasis of skyscrapers, luxury malls, and desert adventures.",
    funPlaces: ["Burj Khalifa", "Dubai Mall", "Dubai Desert", "Palm Jumeirah", "Dubai Marina"],
    similarDestinations: ["abu-dhabi-uae", "doha-qatar", "singapore-singapore"],
    moods: ["excited", "party", "adventurous", "happy"],
    region: "Asia",
  },
  {
    slug: "hanoi-vietnam",
    city: "Hanoi",
    country: "Vietnam",
    countryCode: "VN",
    lat: 21.0285,
    lon: 105.8542,
    description: "Ancient pagodas, bustling streets, and the world's best pho.",
    funPlaces: ["Hoan Kiem Lake", "Old Quarter of Hanoi", "Ho Chi Minh Mausoleum", "Temple of Literature, Hanoi", "Ha Long Bay"],
    similarDestinations: ["bangkok-thailand", "bali-indonesia", "tokyo-japan"],
    moods: ["foodie", "curious", "adventurous", "cultural"],
    region: "Asia",
  },
  {
    slug: "lisbon-portugal",
    city: "Lisbon",
    country: "Portugal",
    countryCode: "PT",
    lat: 38.7223,
    lon: -9.1393,
    description: "Pastel-colored hills, melancholic fado music, and custard tarts.",
    funPlaces: ["Belém Tower", "Tram 28 (Lisbon)", "Time Out Market Lisboa", "Alfama", "Jerónimos Monastery"],
    similarDestinations: ["barcelona-spain", "porto-portugal", "seville-spain"],
    moods: ["sad", "romantic", "relaxed", "foodie"],
    region: "Europe",
  },
  {
    slug: "nairobi-kenya",
    city: "Nairobi",
    country: "Kenya",
    countryCode: "KE",
    lat: -1.2921,
    lon: 36.8219,
    description: "Gateway to African safaris — where wildlife roams free.",
    funPlaces: ["Nairobi National Park", "Giraffe Centre, Nairobi", "Karen Blixen Museum", "Maasai Mara", "Sheldrick Wildlife Trust"],
    similarDestinations: ["cape-town-south-africa", "dar-es-salaam-tanzania", "kampala-uganda"],
    moods: ["nature", "adventurous", "excited", "curious"],
    region: "Africa",
  },
  {
    slug: "santorini-greece",
    city: "Santorini",
    country: "Greece",
    countryCode: "GR",
    lat: 36.3932,
    lon: 25.4615,
    description: "White-washed cliffs over impossibly blue seas — a sunset lover's dream.",
    funPlaces: ["Oia", "Red Beach (Santorini)", "Akrotiri (prehistoric city)", "Santorini Wineries", "Fira"],
    similarDestinations: ["mykonos-greece", "amalfi-italy", "dubrovnik-croatia"],
    moods: ["romantic", "relaxed", "happy", "spiritual"],
    region: "Europe",
  },
  {
    slug: "seoul-south-korea",
    city: "Seoul",
    country: "South Korea",
    countryCode: "KR",
    lat: 37.5665,
    lon: 126.978,
    description: "K-pop capital meets centuries-old palaces — tradition and trend collide.",
    funPlaces: ["Gyeongbokgung Palace", "Myeongdong", "N Seoul Tower", "Bukchon Hanok Village", "Hongdae"],
    similarDestinations: ["tokyo-japan", "taipei-taiwan", "osaka-japan"],
    moods: ["excited", "foodie", "party", "curious"],
    region: "Asia",
  },
  {
    slug: "havana-cuba",
    city: "Havana",
    country: "Cuba",
    countryCode: "CU",
    lat: 23.1136,
    lon: -82.3666,
    description: "Vintage cars, salsa rhythms, and colonial architecture frozen in time.",
    funPlaces: ["Malecón, Havana", "Old Havana", "Havana Cathedral", "Tropicana Club", "El Floridita"],
    similarDestinations: ["rio-de-janeiro-brazil", "cartagena-colombia", "san-juan-puerto-rico"],
    moods: ["party", "cultural", "romantic", "happy"],
    region: "North America",
  },
  {
    slug: "singapore-singapore",
    city: "Singapore",
    country: "Singapore",
    countryCode: "SG",
    lat: 1.3521,
    lon: 103.8198,
    description: "A garden city of futuristic architecture and legendary hawker food.",
    funPlaces: ["Gardens by the Bay", "Marina Bay Sands", "Hawker centre", "Sentosa", "Little India, Singapore"],
    similarDestinations: ["tokyo-japan", "dubai-uae", "hong-kong-china"],
    moods: ["foodie", "excited", "curious", "happy"],
    region: "Asia",
  },
  {
    slug: "petra-jordan",
    city: "Petra",
    country: "Jordan",
    countryCode: "JO",
    lat: 30.3285,
    lon: 35.4444,
    description: "The Rose City — an ancient wonder carved into sandstone cliffs.",
    funPlaces: ["Al-Khazneh", "Ad Deir", "Siq", "Petra", "Royal Tombs (Petra)"],
    similarDestinations: ["cairo-egypt", "marrakech-morocco", "istanbul-turkey"],
    moods: ["adventurous", "spiritual", "curious", "nature"],
    region: "Asia",
  },
  {
    slug: "vancouver-canada",
    city: "Vancouver",
    country: "Canada",
    countryCode: "CA",
    lat: 49.2827,
    lon: -123.1207,
    description: "Mountains meet ocean — a nature lover's urban paradise.",
    funPlaces: ["Stanley Park", "Granville Island", "Grouse Mountain", "Gastown", "Capilano Suspension Bridge"],
    similarDestinations: ["seattle-usa", "portland-usa", "toronto-canada"],
    moods: ["nature", "relaxed", "happy", "adventurous"],
    region: "North America",
  },
  {
    slug: "osaka-japan",
    city: "Osaka",
    country: "Japan",
    countryCode: "JP",
    lat: 34.6937,
    lon: 135.5023,
    description: "Japan's kitchen — neon-lit streets, bold street food, and an unmatched nightlife energy.",
    funPlaces: ["Osaka Castle", "Dōtonbori", "Shinsekai", "Kuromon Market", "Universal Studios Japan"],
    similarDestinations: ["tokyo-japan", "kyoto-japan", "seoul-south-korea"],
    moods: ["foodie", "party", "excited", "happy"],
    region: "Asia",
  },
  {
    slug: "florence-italy",
    city: "Florence",
    country: "Italy",
    countryCode: "IT",
    lat: 43.7696,
    lon: 11.2558,
    description: "The cradle of the Renaissance — art, architecture, and Tuscan sunsets.",
    funPlaces: ["Florence Cathedral", "Uffizi Gallery", "Ponte Vecchio", "Piazzale Michelangelo", "Boboli Gardens"],
    similarDestinations: ["rome-italy", "venice-italy", "barcelona-spain"],
    moods: ["cultural", "romantic", "curious", "happy"],
    region: "Europe",
  },
  {
    slug: "vienna-austria",
    city: "Vienna",
    country: "Austria",
    countryCode: "AT",
    lat: 48.2082,
    lon: 16.3738,
    description: "Imperial grandeur, classical music, and the world's finest coffee house culture.",
    funPlaces: ["Schönbrunn Palace", "St. Stephen's Cathedral", "Belvedere Museum", "Naschmarkt", "Vienna State Opera"],
    similarDestinations: ["prague-czech-republic", "budapest-hungary", "munich-germany"],
    moods: ["cultural", "romantic", "relaxed", "curious"],
    region: "Europe",
  },
  {
    slug: "budapest-hungary",
    city: "Budapest",
    country: "Hungary",
    countryCode: "HU",
    lat: 47.4979,
    lon: 19.0402,
    description: "The Pearl of the Danube — thermal baths, ruin bars, and stunning architecture.",
    funPlaces: ["Széchenyi Thermal Bath", "Hungarian Parliament Building", "Fisherman's Bastion", "Ruin bars of Budapest", "Buda Castle"],
    similarDestinations: ["prague-czech-republic", "vienna-austria", "krakow-poland"],
    moods: ["party", "cultural", "romantic", "relaxed"],
    region: "Europe",
  },
  {
    slug: "athens-greece",
    city: "Athens",
    country: "Greece",
    countryCode: "GR",
    lat: 37.9838,
    lon: 23.7275,
    description: "The birthplace of democracy — ancient ruins against a modern Mediterranean backdrop.",
    funPlaces: ["Acropolis of Athens", "Parthenon", "Plaka", "Temple of Olympian Zeus", "National Archaeological Museum, Athens"],
    similarDestinations: ["rome-italy", "istanbul-turkey", "santorini-greece"],
    moods: ["cultural", "curious", "spiritual", "adventurous"],
    region: "Europe",
  },
  {
    slug: "hong-kong-china",
    city: "Hong Kong",
    country: "China",
    countryCode: "HK",
    lat: 22.3193,
    lon: 114.1694,
    description: "A vertical city where bamboo scaffolding meets glass towers and dim sum is an art form.",
    funPlaces: ["Victoria Peak", "Star Ferry", "Temple Street Night Market", "Tian Tan Buddha", "Hong Kong Disneyland"],
    similarDestinations: ["singapore-singapore", "tokyo-japan", "taipei-taiwan"],
    moods: ["excited", "foodie", "curious", "party"],
    region: "Asia",
  },
  {
    slug: "taipei-taiwan",
    city: "Taipei",
    country: "Taiwan",
    countryCode: "TW",
    lat: 25.033,
    lon: 121.5654,
    description: "Night markets, bubble tea, and a skyline crowned by Taipei 101.",
    funPlaces: ["Taipei 101", "Shilin Night Market", "Jiufen", "Longshan Temple", "Elephant Mountain"],
    similarDestinations: ["tokyo-japan", "hong-kong-china", "seoul-south-korea"],
    moods: ["foodie", "curious", "happy", "excited"],
    region: "Asia",
  },
  {
    slug: "copenhagen-denmark",
    city: "Copenhagen",
    country: "Denmark",
    countryCode: "DK",
    lat: 55.6761,
    lon: 12.5683,
    description: "Hygge capital — colorful harbors, bicycles, and world-class Nordic cuisine.",
    funPlaces: ["Nyhavn", "Tivoli Gardens", "The Little Mermaid (statue)", "Christiania", "Rosenborg Castle"],
    similarDestinations: ["amsterdam-netherlands", "stockholm-sweden", "helsinki-finland"],
    moods: ["relaxed", "happy", "foodie", "curious"],
    region: "Europe",
  },
  {
    slug: "dubrovnik-croatia",
    city: "Dubrovnik",
    country: "Croatia",
    countryCode: "HR",
    lat: 42.6507,
    lon: 18.0944,
    description: "The Pearl of the Adriatic — medieval walls above turquoise seas.",
    funPlaces: ["Walls of Dubrovnik", "Old Town Dubrovnik", "Lokrum", "Stradun", "Fort Lovrijenac"],
    similarDestinations: ["santorini-greece", "venice-italy", "split-croatia"],
    moods: ["romantic", "cultural", "relaxed", "happy"],
    region: "Europe",
  },
  {
    slug: "mexico-city-mexico",
    city: "Mexico City",
    country: "Mexico",
    countryCode: "MX",
    lat: 19.4326,
    lon: -99.1332,
    description: "A sprawling megalopolis of ancient Aztec roots, muralism, and world-class street tacos.",
    funPlaces: ["Zócalo", "Frida Kahlo Museum", "Chapultepec Castle", "Teotihuacan", "Coyoacán"],
    similarDestinations: ["buenos-aires-argentina", "havana-cuba", "bogota-colombia"],
    moods: ["cultural", "foodie", "adventurous", "curious"],
    region: "North America",
  },
  {
    slug: "edinburgh-uk",
    city: "Edinburgh",
    country: "United Kingdom",
    countryCode: "GB",
    lat: 55.9533,
    lon: -3.1883,
    description: "A city of gothic spires, whisky, and legends hidden in cobblestone alleys.",
    funPlaces: ["Edinburgh Castle", "Arthur's Seat", "Royal Mile", "Calton Hill", "Scotch Whisky Experience"],
    similarDestinations: ["london-uk", "dublin-ireland", "reykjavik-iceland"],
    moods: ["cultural", "sad", "curious", "adventurous"],
    region: "Europe",
  },
  {
    slug: "phuket-thailand",
    city: "Phuket",
    country: "Thailand",
    countryCode: "TH",
    lat: 7.8804,
    lon: 98.3923,
    description: "Thailand's tropical jewel — limestone karsts, turquoise lagoons, and beach parties.",
    funPlaces: ["Phi Phi Islands", "Patong Beach", "Big Buddha Phuket", "Phang Nga Bay", "Old Phuket Town"],
    similarDestinations: ["bali-indonesia", "bangkok-thailand", "colombo-sri-lanka"],
    moods: ["relaxed", "party", "nature", "adventurous"],
    region: "Asia",
  },
  {
    slug: "seville-spain",
    city: "Seville",
    country: "Spain",
    countryCode: "ES",
    lat: 37.3891,
    lon: -5.9845,
    description: "Flamenco, tapas, and Moorish palaces beneath the Andalusian sun.",
    funPlaces: ["Real Alcázar of Seville", "Plaza de España, Seville", "Seville Cathedral", "Metropol Parasol", "Triana, Seville"],
    similarDestinations: ["barcelona-spain", "lisbon-portugal", "marrakech-morocco"],
    moods: ["romantic", "cultural", "foodie", "happy"],
    region: "Europe",
  },
  {
    slug: "agra-india",
    city: "Agra",
    country: "India",
    countryCode: "IN",
    lat: 27.1767,
    lon: 78.0081,
    description: "Home to the Taj Mahal — the world's most iconic monument to love.",
    funPlaces: ["Taj Mahal", "Agra Fort", "Fatehpur Sikri", "Mehtab Bagh", "Itimad-ud-Daulah"],
    similarDestinations: ["jaipur-india", "varanasi-india", "kathmandu-nepal"],
    moods: ["romantic", "spiritual", "cultural", "curious"],
    region: "Asia",
  },
  {
    slug: "venice-italy",
    city: "Venice",
    country: "Italy",
    countryCode: "IT",
    lat: 45.4408,
    lon: 12.3155,
    description: "A floating city of canals, gondolas, and Renaissance masterpieces.",
    funPlaces: ["St. Mark's Basilica", "Grand Canal", "Rialto Bridge", "Doge's Palace", "Murano"],
    similarDestinations: ["florence-italy", "rome-italy", "dubrovnik-croatia"],
    moods: ["romantic", "cultural", "relaxed", "sad"],
    region: "Europe",
  },
  {
    slug: "queenstown-new-zealand",
    city: "Queenstown",
    country: "New Zealand",
    countryCode: "NZ",
    lat: -45.0312,
    lon: 168.6626,
    description: "The adventure capital of the world — bungee, skiing, and jaw-dropping fjords.",
    funPlaces: ["Milford Sound", "Skyline Queenstown", "Lake Wakatipu", "Remarkables Ski Area", "Queenstown Gardens"],
    similarDestinations: ["sydney-australia", "reykjavik-iceland", "vancouver-canada"],
    moods: ["adventurous", "nature", "excited", "happy"],
    region: "Oceania",
  },
  {
    slug: "zanzibar-tanzania",
    city: "Zanzibar City",
    country: "Tanzania",
    countryCode: "TZ",
    lat: -6.1659,
    lon: 39.2026,
    description: "Spice-scented breezes, powder-white beaches, and Stone Town's winding alleys.",
    funPlaces: ["Stone Town", "Nungwi Beach", "Spice farms of Zanzibar", "Prison Island", "Jozani Forest"],
    similarDestinations: ["nairobi-kenya", "cape-town-south-africa", "bali-indonesia"],
    moods: ["relaxed", "nature", "romantic", "adventurous"],
    region: "Africa",
  },
  {
    slug: "cartagena-colombia",
    city: "Cartagena",
    country: "Colombia",
    countryCode: "CO",
    lat: 10.391,
    lon: -75.5144,
    description: "Colonial walls, Caribbean color, and cumbia rhythms under the palms.",
    funPlaces: ["Walled City of Cartagena", "Rosario Islands", "Castillo San Felipe de Barajas", "Getsemaní", "Café del Mar, Cartagena"],
    similarDestinations: ["havana-cuba", "rio-de-janeiro-brazil", "mexico-city-mexico"],
    moods: ["romantic", "party", "cultural", "happy"],
    region: "South America",
  },
  {
    slug: "jaipur-india",
    city: "Jaipur",
    country: "India",
    countryCode: "IN",
    lat: 26.9124,
    lon: 75.7873,
    description: "The Pink City — a kaleidoscope of forts, palaces, and bazaars in Rajasthan.",
    funPlaces: ["Amber Fort", "Hawa Mahal", "City Palace, Jaipur", "Jantar Mantar, Jaipur", "Nahargarh Fort"],
    similarDestinations: ["agra-india", "marrakech-morocco", "cairo-egypt"],
    moods: ["cultural", "adventurous", "curious", "spiritual"],
    region: "Asia",
  },
];

// Mood to destination matching algorithm
export function getDestinationsByMood(moodId: string): Destination[] {
  // Primary matches: destinations that have this mood
  const primary = destinations.filter((d) => d.moods.includes(moodId));

  // Sort by how prominently the mood features (earlier in moods array = more relevant)
  primary.sort((a, b) => {
    const aIndex = a.moods.indexOf(moodId);
    const bIndex = b.moods.indexOf(moodId);
    return aIndex - bIndex;
  });

  return primary;
}

export function getRandomDestination(): Destination {
  return destinations[Math.floor(Math.random() * destinations.length)];
}

export function getDestinationBySlug(slug: string): Destination | undefined {
  return destinations.find((d) => d.slug === slug);
}

// Top destinations for the "popular" section
export const popularDestinations = [
  "paris-france",
  "tokyo-japan",
  "rome-italy",
  "new-york-usa",
  "london-uk",
  "barcelona-spain",
  "bali-indonesia",
  "istanbul-turkey",
  "dubai-uae",
  "bangkok-thailand",
  "santorini-greece",
  "sydney-australia",
  "rio-de-janeiro-brazil",
  "singapore-singapore",
  "cape-town-south-africa",
  "prague-czech-republic",
  "marrakech-morocco",
  "kyoto-japan",
  "amsterdam-netherlands",
  "cusco-peru",
  "venice-italy",
  "hong-kong-china",
  "agra-india",
  "budapest-hungary",
  "florence-italy",
  "mexico-city-mexico",
  "dubrovnik-croatia",
  "athens-greece",
  "copenhagen-denmark",
  "osaka-japan",
];
